apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Path(`/whoami`)
      kind: Rule
      services:
        - name: whoami
          port: 80
